const router=require("express").Router();
const PolicyServiceRequest=require("../models/PolicyServiceRequest");
const PlanPurchase=require("../models/PlanPurchase");
const Policy=require("../models/Policy");
const auth=require("../middleware/auth");
const STAFF=["admin","bm","unit_manager","agency_manager","agent"];
const clean=(v,n=500)=>String(v||"").trim().slice(0,n);
router.get("/",auth(),async(req,res)=>{try{const q=req.user.role==="customer"?{customerId:req.user.id}:{};res.json(await PolicyServiceRequest.find(q).sort({createdAt:-1}))}catch(e){res.status(500).json({message:"Service requests load failed"})}});
router.post("/",auth(["customer"]),async(req,res)=>{try{
 const policyNumber=clean(req.body.policyNumber,80),requestType=clean(req.body.requestType,40),requestedValue=clean(req.body.requestedValue,1000);
 if(!policyNumber||!requestedValue||!["Nominee Change","Address Change","Contact Update","Bank Update","Other"].includes(requestType))return res.status(400).json({message:"Complete valid service request details"});
 const [purchase,policy]=await Promise.all([PlanPurchase.findOne({customerId:req.user.id,policyNumber}),Policy.findOne({customerId:req.user.id,policyNumber})]);
 if(!purchase&&!policy)return res.status(403).json({message:"Policy does not belong to this customer"});
 const open=await PolicyServiceRequest.findOne({customerId:req.user.id,policyNumber,requestType,status:{$in:["Submitted","Under Review"]}});
 if(open)return res.status(409).json({message:"An open request of this type already exists for this policy"});
 const item=await PolicyServiceRequest.create({customerId:req.user.id,policyNumber,requestType,currentValue:clean(req.body.currentValue,1000),requestedValue,customerRemarks:clean(req.body.customerRemarks),status:"Submitted"});
 res.status(201).json(item);
}catch(e){console.error(e);res.status(500).json({message:"Service request submission failed"})}});
router.patch("/:id/review",auth(STAFF),async(req,res)=>{try{const item=await PolicyServiceRequest.findById(req.params.id);if(!item)return res.status(404).json({message:"Request not found"});const status=clean(req.body.status,20),remarks=clean(req.body.adminRemarks);if(!["Under Review","Approved","Rejected"].includes(status))return res.status(400).json({message:"Invalid review status"});if(status==="Rejected"&&!remarks)return res.status(400).json({message:"Rejection reason is required"});item.status=status;item.adminRemarks=remarks;item.reviewedBy=req.user.id;item.reviewedAt=new Date();await item.save();res.json(item)}catch(e){res.status(500).json({message:"Service request review failed"})}});
module.exports=router;