import { Link, useLocation } from "react-router-dom";

const content: Record<string,{title:string;intro:string;items:string[]}> = {
  "/terms": {title:"Terms of Use",intro:"These terms explain the rules for using the SecureLife digital insurance portal.",items:["Plan illustrations and quotations shown in the portal are based on the information entered and the plan configuration available at that time.","A quotation is not a policy contract. Cover becomes active only after successful payment verification, policy issuance and any applicable underwriting or KYC requirements.","Customers should review policy schedules, premium dates, benefits, exclusions and nominee details after issue and report any discrepancy through the authenticated service channel.","Users must provide accurate information and must not misuse another person's identity, documents or payment details."]},
  "/refund-policy": {title:"Cancellation & Refund Information",intro:"Cancellation or refund requests are handled according to the applicable product terms, free-look conditions and payment status.",items:["Do not make a second payment when a transaction is pending or money has been debited but verification is incomplete.","Use Policy Services or Help & Support with the policy/order reference for a payment or cancellation query.","Eligibility, deductions, timelines and refund method can vary by product and the applicable policy terms.","A displayed free-look period is subject to the issued policy wording and applicable requirements."]},
  "/grievance": {title:"Grievance & Support",intro:"SecureLife provides authenticated service channels for policy, KYC, payment and claim-related concerns.",items:["For account-specific help, sign in and use Help & Support or Policy Services so the request can be linked to your account.","Include the policy number, quotation number, order/receipt reference or claim reference when available. Never send passwords or OTPs.","For a payment marked pending after debit, avoid paying again until the transaction status has been checked.","Keep copies of submitted requests and supporting documents for your records."]}
};
export default function LegalInfo(){
 const {pathname}=useLocation(); const page=content[pathname]||content["/terms"];
 return <main className="legal-page"><section className="legal-card"><Link to="/" className="public-brand"><span>S</span>SecureLife</Link><p className="eyebrow">CUSTOMER INFORMATION</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p><div className="legal-points">{page.items.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b><p>{x}</p></div>)}</div><div className="legal-actions"><Link to="/help" className="btn small-btn">Help & Support</Link><Link to="/privacy-policy" className="mini-btn">Privacy Policy</Link></div><small>Last updated: 02 October 2026</small></section></main>;
}