import { useCallback,useEffect,useMemo,useState } from "react";
import MainLayout from "../layouts/MainLayout";import api from "../services/api";
type Req={_id:string;surrenderRequest?:{paidPremiumAmount:number;policyYear:number;estimatedValue:number;approvedValue:number;eligibleFromPolicyYear:number;settlementStatus:string;settledAt?:string};financialRequest?:{requestedAmount:number;eligibleAmount:number;approvedAmount:number;paidPremiumAmount:number;eligibleFromPolicyYear:number;settlementStatus:string;settledAt?:string};coverEnhancement?:{currentCover:number;requestedCover:number;currentPremium:number;estimatedPremium:number;effectiveDate?:string};policyNumber:string;requestType:string;currentValue?:string;requestedValue:string;customerRemarks?:string;status:string;adminRemarks?:string;createdAt:string};
type Plan={policyNumber?:string;planName:string;policyStatus:string;coverageAmount?:number;yearlyPremium?:number};
export default function PolicyServices(){
 const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem("insuranceUser")||"{}")}catch{return {}}},[]),isCustomer=user.role==="customer";
 const [items,setItems]=useState<Req[]>([]),[plans,setPlans]=useState<Plan[]>([]),[form,setForm]=useState({policyNumber:"",requestType:"Nominee Change",currentValue:"",requestedValue:"",customerRemarks:"",requestedCover:"",requestedAmount:""});
 const load=useCallback(async()=>{const [r,p]=await Promise.all([api.get<Req[]>("/policy-services"),isCustomer?api.get<Plan[]>("/plan-purchases/my-plans"):Promise.resolve({data:[] as Plan[]})]);setItems(r.data);setPlans(p.data)},[isCustomer]);useEffect(()=>{void load()},[load]);
 const submit=async()=>{const financial=["Policy Loan","Partial Withdrawal"].includes(form.requestType),surrender=form.requestType==="Surrender Policy";if(!form.policyNumber||(form.requestType==="Cover Enhancement"?!form.requestedCover:financial?!form.requestedAmount:surrender?false:!form.requestedValue))return alert("Select policy and enter requested details");try{const r=await api.post<Req>("/policy-services",{...form,requestedValue:form.requestType==="Cover Enhancement"?form.requestedCover:["Policy Loan","Partial Withdrawal"].includes(form.requestType)?form.requestedAmount:form.requestType==="Surrender Policy"?"Request policy surrender":form.requestedValue,requestedCover:Number(form.requestedCover||0),requestedAmount:Number(form.requestedAmount||0)});setItems(x=>[r.data,...x]);setForm(x=>({...x,currentValue:"",requestedValue:"",customerRemarks:"",requestedCover:"",requestedAmount:""}));alert("Service request submitted")}catch{alert("Service request submission failed or a similar request is already open")}};
 const settle=async(x:Req)=>{try{const r=await api.patch<Req>(`/policy-services/${x._id}/settlement`,{settlementStatus:"Paid"});setItems(v=>v.map(i=>i._id===x._id?r.data:i))}catch{alert("Settlement update failed")}};
 const review=async(x:Req,status:"Under Review"|"Approved"|"Rejected")=>{let approvedAmount: number|undefined;if(status==="Approved"&&["Policy Loan","Partial Withdrawal","Surrender Policy"].includes(x.requestType)){const raw=window.prompt("Approved amount",String(x.requestType==="Surrender Policy"?x.surrenderRequest?.estimatedValue||"":x.financialRequest?.requestedAmount||""));if(!raw)return;approvedAmount=Number(raw);if(!Number.isFinite(approvedAmount)||approvedAmount<=0)return alert("Enter valid approved amount")}const adminRemarks=window.prompt(status==="Rejected"?"Enter rejection reason":"Admin remarks",status==="Approved"?"Request verified and approved":"");if(status==="Rejected"&&!adminRemarks)return;try{const r=await api.patch<Req>(`/policy-services/${x._id}/review`,{status,adminRemarks:adminRemarks||"",approvedAmount});setItems(v=>v.map(i=>i._id===x._id?r.data:i))}catch{alert("Review failed")}};
 return <MainLayout title={isCustomer?"Policy Services":"Policy Service Requests"} subtitle={isCustomer?"Request updates to your active policy details":"Review customer policy servicing requests"}>
 {isCustomer&&<div className="section"><span className="eyebrow">SELF SERVICE</span><h2>Request a policy update</h2><p className="section-copy">Submit a servicing request. Your policy is not changed automatically; the request remains tracked until reviewed.</p><div className="form-grid">
 <select value={form.policyNumber} onChange={e=>setForm(v=>({...v,policyNumber:e.target.value}))}><option value="">Select Policy</option>{plans.filter(p=>p.policyNumber).map(p=><option key={p.policyNumber} value={p.policyNumber}>{p.policyNumber} — {p.planName}</option>)}</select>
 <select value={form.requestType} onChange={e=>setForm(v=>({...v,requestType:e.target.value}))}><option>Nominee Change</option><option>Address Change</option><option>Contact Update</option><option>Bank Update</option><option>Cover Enhancement</option><option>Policy Loan</option><option>Partial Withdrawal</option><option>Surrender Policy</option><option>Other</option></select>
 {form.requestType==="Cover Enhancement"?<><input disabled value={(()=>{const p=plans.find(x=>x.policyNumber===form.policyNumber);return p?`Current Cover ₹${Number(p.coverageAmount||0).toLocaleString("en-IN")}`:"Select policy first"})()} /><input type="number" placeholder="Requested New Cover Amount" value={form.requestedCover} onChange={e=>setForm(v=>({...v,requestedCover:e.target.value}))}/></>:form.requestType==="Surrender Policy"?<><input disabled value="Eligibility and estimated surrender value are calculated from approved plan rules"/><input disabled value="Final surrender value requires admin approval"/></>:["Policy Loan","Partial Withdrawal"].includes(form.requestType)?<><input type="number" placeholder="Requested Amount" value={form.requestedAmount} onChange={e=>setForm(v=>({...v,requestedAmount:e.target.value}))}/><input disabled value="Eligibility is checked from admin-approved plan rules on submit"/></>:<><input placeholder="Current details (optional)" value={form.currentValue} onChange={e=>setForm(v=>({...v,currentValue:e.target.value}))}/><input placeholder="Requested new details" value={form.requestedValue} onChange={e=>setForm(v=>({...v,requestedValue:e.target.value}))}/></>}<input placeholder="Remarks (optional)" value={form.customerRemarks} onChange={e=>setForm(v=>({...v,customerRemarks:e.target.value}))}/></div><button className="btn small-btn" onClick={()=>void submit()}>Submit Service Request</button></div>}
 <div className="section"><div className="section-heading-row"><div><span className="eyebrow">REQUEST TRACKER</span><h2>{isCustomer?"My service history":"Customer service queue"}</h2></div><button className="mini-btn" onClick={()=>void load()}>Refresh</button></div>
 {items.length===0?<p>No service requests found.</p>:<div className="premium-table-wrap"><table className="table"><thead><tr><th>Policy</th><th>Request</th><th>Requested Change</th><th>Status</th><th>Remarks</th>{!isCustomer&&<th>Review</th>}</tr></thead><tbody>{items.map(x=><tr key={x._id}><td>{x.policyNumber}<br/><small>{new Date(x.createdAt).toLocaleDateString("en-IN")}</small></td><td><strong>{x.requestType}</strong><br/><small>{x.currentValue||"No current value supplied"}</small></td><td>{x.requestType==="Cover Enhancement"&&x.coverEnhancement?<><strong>₹{Number(x.coverEnhancement.currentCover).toLocaleString("en-IN")} → ₹{Number(x.coverEnhancement.requestedCover).toLocaleString("en-IN")}</strong><br/><small>Estimated premium: ₹{Number(x.coverEnhancement.currentPremium).toLocaleString("en-IN")} → ₹{Number(x.coverEnhancement.estimatedPremium).toLocaleString("en-IN")}</small></>:x.requestType==="Surrender Policy"&&x.surrenderRequest?<><strong>Estimated ₹{Number(x.surrenderRequest.estimatedValue||0).toLocaleString("en-IN")}</strong><br/><small>Paid premiums ₹{Number(x.surrenderRequest.paidPremiumAmount||0).toLocaleString("en-IN")} · Policy year {x.surrenderRequest.policyYear} · Approved ₹{Number(x.surrenderRequest.approvedValue||0).toLocaleString("en-IN")} · {x.surrenderRequest.settlementStatus}</small></>:["Policy Loan","Partial Withdrawal"].includes(x.requestType)&&x.financialRequest?<><strong>Requested ₹{Number(x.financialRequest.requestedAmount||0).toLocaleString("en-IN")}</strong><br/><small>Eligible ₹{Number(x.financialRequest.eligibleAmount||0).toLocaleString("en-IN")} · Approved ₹{Number(x.financialRequest.approvedAmount||0).toLocaleString("en-IN")} · Settlement {x.financialRequest.settlementStatus}</small></>:x.requestedValue}</td><td><span className="secure-chip">{x.status}</span></td><td>{x.adminRemarks||x.customerRemarks||"—"}</td>{!isCustomer&&<td>{x.status==="Approved"&&["Policy Loan","Partial Withdrawal","Surrender Policy"].includes(x.requestType)&&((x.requestType==="Surrender Policy"?x.surrenderRequest?.settlementStatus:x.financialRequest?.settlementStatus)!=="Paid")?<button className="mini-btn" onClick={()=>void settle(x)}>Mark Paid</button>:["Submitted","Under Review"].includes(x.status)?<><button className="mini-btn" onClick={()=>void review(x,"Approved")}>Approve</button> <button className="mini-btn" onClick={()=>void review(x,"Rejected")}>Reject</button>{x.status==="Submitted"&&<><br/><button className="mini-btn" onClick={()=>void review(x,"Under Review")}>Under Review</button></>}</>:<span>Reviewed</span>}</td>}</tr>)}</tbody></table></div>}</div>
 </MainLayout>
}