import { useCallback,useEffect,useMemo,useState } from "react";
import MainLayout from "../layouts/MainLayout";import api from "../services/api";
type Req={_id:string;policyNumber:string;requestType:string;currentValue?:string;requestedValue:string;customerRemarks?:string;status:string;adminRemarks?:string;createdAt:string};
type Plan={policyNumber?:string;planName:string;policyStatus:string};
export default function PolicyServices(){
 const user=useMemo(()=>{try{return JSON.parse(localStorage.getItem("insuranceUser")||"{}")}catch{return {}}},[]),isCustomer=user.role==="customer";
 const [items,setItems]=useState<Req[]>([]),[plans,setPlans]=useState<Plan[]>([]),[form,setForm]=useState({policyNumber:"",requestType:"Nominee Change",currentValue:"",requestedValue:"",customerRemarks:""});
 const load=useCallback(async()=>{const [r,p]=await Promise.all([api.get<Req[]>("/policy-services"),isCustomer?api.get<Plan[]>("/plan-purchases/my-plans"):Promise.resolve({data:[] as Plan[]})]);setItems(r.data);setPlans(p.data)},[isCustomer]);useEffect(()=>{void load()},[load]);
 const submit=async()=>{if(!form.policyNumber||!form.requestedValue)return alert("Select policy and enter requested change");try{const r=await api.post<Req>("/policy-services",form);setItems(x=>[r.data,...x]);setForm(x=>({...x,currentValue:"",requestedValue:"",customerRemarks:""}));alert("Service request submitted")}catch{alert("Service request submission failed or a similar request is already open")}};
 const review=async(x:Req,status:"Under Review"|"Approved"|"Rejected")=>{const adminRemarks=window.prompt(status==="Rejected"?"Enter rejection reason":"Admin remarks",status==="Approved"?"Request verified and approved":"");if(status==="Rejected"&&!adminRemarks)return;try{const r=await api.patch<Req>(`/policy-services/${x._id}/review`,{status,adminRemarks:adminRemarks||""});setItems(v=>v.map(i=>i._id===x._id?r.data:i))}catch{alert("Review failed")}};
 return <MainLayout title={isCustomer?"Policy Services":"Policy Service Requests"} subtitle={isCustomer?"Request updates to your active policy details":"Review customer policy servicing requests"}>
 {isCustomer&&<div className="section"><span className="eyebrow">SELF SERVICE</span><h2>Request a policy update</h2><p className="section-copy">Submit a servicing request. Your policy is not changed automatically; the request remains tracked until reviewed.</p><div className="form-grid">
 <select value={form.policyNumber} onChange={e=>setForm(v=>({...v,policyNumber:e.target.value}))}><option value="">Select Policy</option>{plans.filter(p=>p.policyNumber).map(p=><option key={p.policyNumber} value={p.policyNumber}>{p.policyNumber} — {p.planName}</option>)}</select>
 <select value={form.requestType} onChange={e=>setForm(v=>({...v,requestType:e.target.value}))}><option>Nominee Change</option><option>Address Change</option><option>Contact Update</option><option>Bank Update</option><option>Other</option></select>
 <input placeholder="Current details (optional)" value={form.currentValue} onChange={e=>setForm(v=>({...v,currentValue:e.target.value}))}/><input placeholder="Requested new details" value={form.requestedValue} onChange={e=>setForm(v=>({...v,requestedValue:e.target.value}))}/><input placeholder="Remarks (optional)" value={form.customerRemarks} onChange={e=>setForm(v=>({...v,customerRemarks:e.target.value}))}/></div><button className="btn small-btn" onClick={()=>void submit()}>Submit Service Request</button></div>}
 <div className="section"><div className="section-heading-row"><div><span className="eyebrow">REQUEST TRACKER</span><h2>{isCustomer?"My service history":"Customer service queue"}</h2></div><button className="mini-btn" onClick={()=>void load()}>Refresh</button></div>
 {items.length===0?<p>No service requests found.</p>:<div className="premium-table-wrap"><table className="table"><thead><tr><th>Policy</th><th>Request</th><th>Requested Change</th><th>Status</th><th>Remarks</th>{!isCustomer&&<th>Review</th>}</tr></thead><tbody>{items.map(x=><tr key={x._id}><td>{x.policyNumber}<br/><small>{new Date(x.createdAt).toLocaleDateString("en-IN")}</small></td><td><strong>{x.requestType}</strong><br/><small>{x.currentValue||"No current value supplied"}</small></td><td>{x.requestedValue}</td><td><span className="secure-chip">{x.status}</span></td><td>{x.adminRemarks||x.customerRemarks||"—"}</td>{!isCustomer&&<td>{["Submitted","Under Review"].includes(x.status)?<><button className="mini-btn" onClick={()=>void review(x,"Approved")}>Approve</button> <button className="mini-btn" onClick={()=>void review(x,"Rejected")}>Reject</button>{x.status==="Submitted"&&<><br/><button className="mini-btn" onClick={()=>void review(x,"Under Review")}>Under Review</button></>}</>:<span>Reviewed</span>}</td>}</tr>)}</tbody></table></div>}</div>
 </MainLayout>
}