import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import "../styles/Auth.css";
import api from "../services/api";
import jsPDF from "jspdf";

type Plan={_id:string;planName:string;productGroup?:string;category:string;coverageAmount?:number;paymentYears?:number;policyTermYears?:number;ageMin?:number;ageMax?:number;premiumFrequencies?:string[];maturityAges?:number[];premiumPayingTerms?:number[]};
type Quote={planId:string;planName:string;productGroup:string;age:number;gender:string;smoker:boolean;coverageAmount:number;paymentYears:number;policyTermYears:number;coverTillAge?:number;frequency:string;instalmentPremium:number;annualPremium:number;totalPremium:number;schedule:{policyYear:number;annualPremium:number;frequency:string;instalmentPremium:number}[];benefitType?:string;benefitSchedule?:{policyYear:number;amount:number;type:string}[];maturityAmount?:number;deathBenefit?:number;disclaimer:string};
const groups=["ULIPS","Traditional Products","Term / Health Products","Pension Products","iSolutions","Other"];
const money=(n:number)=>"₹"+Number(n||0).toLocaleString("en-IN");
const err=(e:unknown)=>typeof e==="object"&&e!==null&&"response" in e?(e as {response?:{data?:{message?:string}}}).response?.data?.message||"Quotation failed":"Quotation failed";

export default function PremiumCalculator(){
 const navigate=useNavigate();
 const backToPortal=()=>{try{const u=JSON.parse(localStorage.getItem("insuranceUser")||"{}");if(u.role==="advisor")return navigate("/advisor-dashboard");if(u.role==="customer")return navigate("/customer-dashboard");if(["admin","bm","unit_manager","agency_manager","agent"].includes(u.role))return navigate("/dashboard");}catch{}navigate("/");};
 const [plans,setPlans]=useState<Plan[]>([]),[planId,setPlanId]=useState(""),[age,setAge]=useState("30"),[dob,setDob]=useState(""),[customerName,setCustomerName]=useState(""),[mobile,setMobile]=useState(""),[gender,setGender]=useState("Male"),[smoker,setSmoker]=useState(false),[cover,setCover]=useState(""),[frequency,setFrequency]=useState("Yearly"),[quote,setQuote]=useState<Quote|null>(null),[loading,setLoading]=useState(false),[savedQuoteNumber,setSavedQuoteNumber]=useState(""),[savedQuoteId,setSavedQuoteId]=useState(""),[coverTillAge,setCoverTillAge]=useState(""),[ppt,setPpt]=useState("");
 const quotationNumber=quote?`QT-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${String(quote.planId).slice(-6).toUpperCase()}`:"";
 const quoteDate=new Date();
 const validityDate=new Date(quoteDate.getTime()+15*86400000);
 const changeDob=(value:string)=>{setDob(value);if(!value)return;const d=new Date(value);const now=new Date();let years=now.getFullYear()-d.getFullYear();const m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))years--;if(years>=0)setAge(String(years));};
 const selected=plans.find(p=>p._id===planId);
 const availableMaturityAges=(selected?.maturityAges||[]).filter(x=>x>Number(age));
 const availablePpts=(selected?.premiumPayingTerms?.length?selected.premiumPayingTerms:[selected?.paymentYears||1]).filter(x=>!coverTillAge||x<=Number(coverTillAge)-Number(age));
 useEffect(()=>{void api.get<Plan[]>("/insurance-plans").then(r=>{const data=Array.isArray(r.data)?r.data:[];setPlans(data);if(data[0]){setPlanId(data[0]._id);setCover(String(data[0].coverageAmount||""));}}).catch(()=>setPlans([]));},[]);
 const choose=(id:string)=>{setPlanId(id);const p=plans.find(x=>x._id===id);if(p){setCover(String(p.coverageAmount||""));setFrequency(p.premiumFrequencies?.[0]||"Yearly");const ages=(p.maturityAges||[]).filter(x=>x>Number(age));setCoverTillAge(ages[0]?String(ages[0]):"");setPpt(String(p.premiumPayingTerms?.[0]||p.paymentYears||1));}setQuote(null);};
 const downloadQuote=()=>{if(!quote)return;
  const doc=new jsPDF({unit:"mm",format:"a4"}), W=210, margin=16; const moneyPdf=(n:number)=>"Rs. "+Number(n||0).toLocaleString("en-IN");
  const red=[159,18,57] as [number,number,number], orange=[245,130,32] as [number,number,number], dark=[30,41,59] as [number,number,number], muted=[100,116,139] as [number,number,number];
  const line=()=>{doc.setDrawColor(226,232,240);doc.line(margin,y,W-margin,y);y+=6}; let y=0;
  const header=()=>{doc.setFillColor(...red);doc.rect(0,0,W,28,"F");doc.setFillColor(...orange);doc.rect(0,28,W,2,"F");doc.setTextColor(255,255,255);doc.setFont("helvetica","bold");doc.setFontSize(20);doc.text("SecureLife",margin,13);doc.setFontSize(8);doc.text("INSURANCE  |  SMART QUOTATION",margin,20);doc.setFontSize(9);doc.text("INDICATIVE BENEFIT ILLUSTRATION",W-margin,14,{align:"right"});y=40;};
  const section=(title:string)=>{if(y>260){doc.addPage();header();}doc.setFillColor(255,247,237);doc.roundedRect(margin,y,W-margin*2,9,2,2,"F");doc.setTextColor(...red);doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text(title.toUpperCase(),margin+4,y+6);y+=15;};
  const pair=(l1:string,v1:string,l2:string,v2:string)=>{doc.setFontSize(8);doc.setTextColor(...muted);doc.setFont("helvetica","normal");doc.text(l1,margin,y);doc.text(l2,110,y);doc.setFontSize(10);doc.setTextColor(...dark);doc.setFont("helvetica","bold");doc.text(v1,margin,y+5);doc.text(v2,110,y+5);y+=13;};
  header();doc.setTextColor(...dark);doc.setFont("helvetica","bold");doc.setFontSize(16);doc.text("Personalised Insurance Quotation",margin,y);y+=8;doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(...muted);doc.text(`Quotation No. ${savedQuoteNumber||quotationNumber}`,margin,y);doc.text(`Date: ${quoteDate.toLocaleDateString("en-IN")}`,W-margin,y,{align:"right"});y+=6;doc.text(`Valid until: ${validityDate.toLocaleDateString("en-IN")}`,margin,y);y+=9;line();
  section("Customer Details");pair("Customer Name",customerName||"-","Mobile",mobile||"-");pair("Date of Birth",dob?new Date(dob).toLocaleDateString("en-IN"):"-","Age / Gender",`${quote.age} years / ${quote.gender}`);pair("Smoking Status",quote.smoker?"Smoker":"Non-smoker","Product Category",quote.productGroup||"Other");
  section("Plan Summary");pair("Plan Name",quote.planName,"Benefit / Sum Assured",moneyPdf(quote.coverageAmount));pair("Policy Term",`${quote.policyTermYears} years${quote.coverTillAge?` (till age ${quote.coverTillAge})`:""}`,"Premium Paying Term",`${quote.paymentYears} years`);pair("Payment Mode",quote.frequency,"Instalment Premium",moneyPdf(quote.instalmentPremium));pair("Annual Premium",moneyPdf(quote.annualPremium),"Total Premium",moneyPdf(quote.totalPremium));
  section("Key Benefits");pair("Life / Death Benefit",moneyPdf(quote.deathBenefit||quote.coverageAmount),"Maturity Benefit",quote.maturityAmount?moneyPdf(quote.maturityAmount):"-");if((quote.benefitSchedule||[]).length)pair(quote.benefitType||"Income Benefit",moneyPdf(quote.benefitSchedule?.[0]?.amount||0)+" per payout","Payout Period",`${quote.benefitSchedule?.length||0} years`);
  section("Premium Schedule");doc.setFillColor(248,250,252);doc.rect(margin,y,W-margin*2,8,"F");doc.setTextColor(...dark);doc.setFont("helvetica","bold");doc.setFontSize(8);doc.text("POLICY YEAR",margin+3,y+5);doc.text("MODE",55,y+5);doc.text("INSTALMENT",105,y+5);doc.text("ANNUAL PREMIUM",W-margin-3,y+5,{align:"right"});y+=10;doc.setFont("helvetica","normal");
  quote.schedule.forEach(row=>{if(y>272){doc.addPage();header();}doc.setTextColor(...dark);doc.text(String(row.policyYear),margin+3,y);doc.text(row.frequency,55,y);doc.text(moneyPdf(row.instalmentPremium),105,y);doc.text(moneyPdf(row.annualPremium),W-margin-3,y,{align:"right"});y+=7;doc.setDrawColor(241,245,249);doc.line(margin,y-3,W-margin,y-3);});
  if((quote.benefitSchedule||[]).length){section("Benefit / Income Schedule");(quote.benefitSchedule||[]).forEach(row=>{if(y>272){doc.addPage();header();}doc.setTextColor(...dark);doc.setFontSize(8);doc.text(`Policy Year ${row.policyYear}`,margin+3,y);doc.text(row.type,70,y);doc.text(moneyPdf(row.amount),W-margin-3,y,{align:"right"});y+=7;});}
  if(y>242){doc.addPage();header();}section("Important Note");doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(...muted);const note=doc.splitTextToSize(quote.disclaimer, W-margin*2-8);doc.text(note,margin+4,y);y+=note.length*4+7;doc.setDrawColor(...orange);doc.line(margin,y,W-margin,y);y+=6;doc.setFontSize(7.5);doc.text("This quotation is indicative and is not a policy contract. Final premium and benefits are subject to proposal review, underwriting and applicable policy terms.",margin,y,{maxWidth:W-margin*2});
  const pages=doc.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);doc.setFontSize(7);doc.setTextColor(...muted);doc.text(`SecureLife Insurance  |  ${savedQuoteNumber||quotationNumber}`,margin,291);doc.text(`Page ${p} of ${pages}`,W-margin,291,{align:"right"});}
  doc.save(`${quote.planName.replace(/[^a-z0-9]+/gi,"-")}-quotation.pdf`);
 };
 const saveQuote=async()=>{if(!quote)return;try{const r=await api.post<{quotationNumber:string}>("/quotations",{...quote,customerName,mobile,dob});setSavedQuoteNumber(r.data.quotationNumber);setSavedQuoteId((r.data as {quotationNumber:string;_id?:string})._id||"");alert("Quotation saved: "+r.data.quotationNumber);}catch(e){alert(err(e));}};
 const calculate=async()=>{if(!selected)return;setSavedQuoteNumber("");setSavedQuoteId("");try{setLoading(true);const r=await api.post<Quote>(`/insurance-plans/${selected._id}/quote`,{age:Number(age),gender,smoker,coverageAmount:Number(cover),frequency,coverTillAge:Number(coverTillAge||0),paymentYears:Number(ppt||selected.paymentYears||1)});setQuote(r.data);sessionStorage.setItem("premiumEstimate",JSON.stringify({category:selected.category,coverageAmount:r.data.coverageAmount,yearlyPremium:r.data.annualPremium,planId:selected._id}));}catch(e){alert(err(e));}finally{setLoading(false);}};
 return <div className="calculator-page smart-quote-page"><div className="calculator-shell smart-quote-shell">
  <header className="calculator-header"><Link className="public-brand" to="/"><span>S</span>SecureLife</Link><button type="button" onClick={backToPortal} className="mini-btn">Back to portal</button></header>
  <div className="calculator-intro"><span className="eyebrow">SMART QUOTES</span><h1>Plan-specific insurance quotation</h1><p>Select a product, enter customer details and get premium by age, cover, payment frequency and plan rules.</p></div>
  <div className="section quote-section"><h2>Select Product Category</h2>{groups.map(g=>{const items=plans.filter(p=>(p.productGroup||"Other")===g);if(!items.length)return null;return <details key={g} open={selected?.productGroup===g}><summary style={{cursor:"pointer",fontWeight:700,padding:"12px 0"}}>{g}</summary><div className="cards">{items.map(p=><button key={p._id} className={p._id===planId?"btn small-btn":"mini-btn"} onClick={()=>choose(p._id)}>{p.planName}</button>)}</div></details>;})}</div>
  {selected&&<div className="section quote-section quote-input-section"><span className="eyebrow">CUSTOMER INPUT</span><h2>{selected.planName}</h2><div className="form-grid">
   <input placeholder="Customer Name" value={customerName} onChange={e=>setCustomerName(e.target.value)} />
   <input inputMode="numeric" placeholder="Mobile Number" maxLength={10} value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,"").slice(0,10))} />
   <input type="date" aria-label="Date of Birth" value={dob} onChange={e=>changeDob(e.target.value)} />
   <input type="number" min={selected.ageMin||1} max={selected.ageMax||100} placeholder="Age" value={age} onChange={e=>setAge(e.target.value)}/>
   <select value={gender} onChange={e=>setGender(e.target.value)}><option>Male</option><option>Female</option><option>Other</option></select>
   <input type="number" placeholder="Sum Assured / Benefit Cover" value={cover} onChange={e=>setCover(e.target.value)}/>
   {availableMaturityAges.length>0&&<select aria-label="Cover till age" value={coverTillAge} onChange={e=>{setCoverTillAge(e.target.value);setQuote(null);}}><option value="">Cover Till Age</option>{availableMaturityAges.map(x=><option key={x} value={x}>Cover till age {x} ({x-Number(age)} years)</option>)}</select>}
   <select aria-label="Premium paying term" value={ppt} onChange={e=>{setPpt(e.target.value);setQuote(null);}}>{availablePpts.map(x=><option key={x} value={x}>Pay premium for {x} years</option>)}</select>
   <select value={frequency} onChange={e=>setFrequency(e.target.value)}>{(selected.premiumFrequencies?.length?selected.premiumFrequencies:["Yearly"]).map(x=><option key={x}>{x}</option>)}</select>
   <label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={smoker} onChange={e=>setSmoker(e.target.checked)}/> Smoker</label>
  </div><button className="btn small-btn" style={{marginTop:16}} onClick={()=>void calculate()} disabled={loading}>{loading?"Calculating...":"Generate Smart Quote"}</button></div>}
  {quote&&<div className="section quote-section quote-result-section"><span className="eyebrow">YOUR QUOTATION</span><h2>{quote.planName}</h2><p className="muted-copy">{quotationNumber} · {quoteDate.toLocaleDateString("en-IN")} · Valid until {validityDate.toLocaleDateString("en-IN")}{customerName ? ` · ${customerName}` : ""}</p><div className="cards quote-summary-grid">
   <div className="card quote-summary-card"><h3>You Pay</h3><h1>{money(quote.instalmentPremium)}</h1><p>{quote.frequency}</p></div>
   <div className="card quote-summary-card"><h3>Annual Premium</h3><h1>{money(quote.annualPremium)}</h1></div>
   <div className="card quote-summary-card"><h3>You Get</h3><h1>{money(quote.coverageAmount)}</h1><p>Benefit / Sum Assured</p></div>
   <div className="card quote-summary-card"><h3>Pay For</h3><h1>{quote.paymentYears} years</h1></div>
   <div className="card quote-summary-card"><h3>Policy Term</h3><h1>{quote.policyTermYears} years</h1></div>
  </div>{((quote.benefitSchedule||[]).length>0||quote.maturityAmount||quote.deathBenefit)&&<><h3>Plan Benefits</h3><div className="cards">{quote.deathBenefit?<div className="card"><h3>Life Cover</h3><h1>{money(quote.deathBenefit)}</h1></div>:null}{quote.maturityAmount?<div className="card"><h3>Maturity Benefit</h3><h1>{money(quote.maturityAmount)}</h1></div>:null}{(quote.benefitSchedule||[]).length?<div className="card"><h3>{quote.benefitType||"Income"}</h3><h1>{money(quote.benefitSchedule?.[0]?.amount||0)}</h1><p>per payout · {quote.benefitSchedule?.length} years</p></div>:null}</div>{(quote.benefitSchedule||[]).length?<div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Policy Year</th><th>Benefit</th><th>Amount</th></tr></thead><tbody>{quote.benefitSchedule?.map(x=><tr key={x.policyYear}><td>{x.policyYear}</td><td>{x.type}</td><td>{money(x.amount)}</td></tr>)}</tbody></table></div>:null}</>}<h3>Year-wise premium schedule</h3><div style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Policy Year</th><th>Frequency</th><th>Instalment</th><th>Annual</th></tr></thead><tbody>{quote.schedule.map(x=><tr key={x.policyYear}><td>{x.policyYear}</td><td>{x.frequency}</td><td>{money(x.instalmentPremium)}</td><td>{money(x.annualPremium)}</td></tr>)}</tbody></table></div><p className="muted-copy">{quote.disclaimer}</p><div className="quote-actions"><button className="mini-btn" onClick={downloadQuote}>Download Quotation PDF</button><button className="mini-btn" onClick={()=>void saveQuote()} disabled={!!savedQuoteNumber}>{savedQuoteNumber ? `Saved ${savedQuoteNumber}` : "Save Quotation"}</button><button className="btn small-btn" onClick={()=>{if(!savedQuoteId){alert("Save quotation first to continue with this quote.");return;}sessionStorage.setItem("acceptedQuotation",JSON.stringify({id:savedQuoteId,number:savedQuoteNumber,planId:quote.planId,customerName,mobile,dob}));window.location.href=`/online-policy-purchase?plan=${quote.planId}&quote=${savedQuoteId}`;}}>Proceed to Buy →</button></div></div>}
 </div></div>;
}